### ISSUE TITLE
Please specify all or some of tested workable `ant` versions at the git README.* for seamless building of Bote

### ISSUE THREAD

**Issue by hypnosis-i2p** [i2p/i2p.i2p-bote#9]
Rationale: Ant`s syntax was unstable at ant versions history and some ant build files language syntax/semantics changes were quite erratic. Please trust my non-interrupted industrial enterprise Java experience since 1998 including top 4 planet bank groups and top transnational corps

**Comment by str4d** [comment]
I'm nearly finished migrating the build system to Gradle; once that is done, Ant won't be necessary.

**Comment by str4d** [comment]
The Ant build system has now been replaced by Gradle as part of merging the webapp and Android repositories.
